apiVersion: v1
kind: Service
metadata:
  name: sample-application-svc
  namespace: devops
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: sample-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
